const router = require('express').Router();
const healthRoutes = require('./healthRoutes');
const authRoutes = require('./authRoutes');
const speakerRoutes = require('./speakerRoutes');
const workshopRoutes = require('./workshopRoutes');
const eventRoutes = require('./eventRoutes');
const partnerRoutes = require('./partnerRoutes');
const sponsorshipRoutes = require('./sponsorshipRoutes');
const mediaRoutes = require('./mediaRoutes');
const marketingRoutes = require('./marketingRoutes');
const settingsRoutes = require('./settingsRoutes');
const trailerRoutes = require('./trailerRoutes');
const researchRoutes = require('./researchRoutes');
const registrationRoutes = require('./registrationRoutes');
const paymentRoutes = require('./paymentRoutes');
const operationsRoutes = require('./operationsRoutes');
const logisticsRoutes = require('./logisticsRoutes');
const volunteerRoutes = require('./volunteerRoutes');
const formRoutes = require('./formRoutes');
const mobileRoutes = require('./mobileRoutes');
const coreRoutes = require('./coreRoutes');
const systemRoutes = require('./systemRoutes');
const systemAdminRoutes = require('./systemAdminRoutes');
const superAdminRoutes = require('./superAdminRoutes');
const { optionalAuth } = require('../middleware/authMiddleware');
const { eventContext } = require('../middleware/eventContextMiddleware');

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use(optionalAuth, eventContext);
router.use('/speakers', speakerRoutes);
router.use('/', eventRoutes);
router.use('/workshops', workshopRoutes);
router.use('/', sponsorshipRoutes);
router.use('/partners', partnerRoutes);
router.use('/media', mediaRoutes);
router.use('/', marketingRoutes);
router.use('/settings', settingsRoutes);
router.use('/trailer', trailerRoutes);
router.use('/research', researchRoutes);
router.use('/', paymentRoutes);
router.use('/', operationsRoutes);
router.use('/', volunteerRoutes);
router.use('/', formRoutes);
router.use('/', mobileRoutes);
router.use('/', coreRoutes);
router.use('/', logisticsRoutes);
router.use('/', systemAdminRoutes);
router.use('/', systemRoutes);
router.use('/', registrationRoutes);
router.use('/', superAdminRoutes);

module.exports = router;
